version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    working_directory: ~/Solutions
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # - run:
      #     command: |
      #       git clone -b geekrainy https://github.com/geekrainy/hexo-theme-element.git themes/element
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: |
            yarn
            touch public/.nojekyll
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            yarn build
            yarn deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature_20230913_travis