site_name: Luskyle
copyright: 'Author: <a href="mailto:844804539@qq.com">844804539@qq.com</a>'

theme:
    name: bootstrap
extra_css:
    - style.css
extra_javascript:
    - injection.js
nav:
    - 首页: index.md 
    - Solutions:
        - 数据库: 数据库解决方案合集.md
        - 前端: 前端.md
        - Microsoft.NET: microsoft.net.md